diff --git Makefile Makefile
index a9cd9503..5ab60699 100644
--- Makefile
+++ Makefile
@@ -1,3 +1,7 @@
+# go option
+LDFLAGS     :=
+GOFLAGS     :=
+
 # Image URL to use all building/pushing image targets
 IMAGE_REGISTRY ?= quay.io
 REGISTRY_NAMESPACE ?= cephcsi
@@ -156,7 +160,7 @@ lint-fix: golangci-lint-fix markdownlint-fix## run linters and perform fixes
 
 .PHONY: build
 build: manifests generate fmt vet ## Build manager binary.
-	go build -o bin/manager cmd/main.go
+	go build $(GOFLAGS) -ldflags '$(LDFLAGS)' -o bin/manager cmd/main.go
 
 .PHONY: run
 run: manifests generate fmt vet ## Run a controller from your host.
